---
- name: Validate HTTP response from the server
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}"
    return_content: true
  register: validation_http_response

- name: Assert web server is running and serving expected content
  ansible.builtin.assert:
    that:
      - validation_http_response.status == 200
      - '"A fully responsive site template" in validation_http_response.content'
