---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH (port 22)
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow HTTP (port 80)
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Ensure UFW is enabled and will start on boot
  community.general.ufw:
    state: enabled
