---
- name: Provision and Configure Secure Web Server on DigitalOcean
  hosts: localhost
  gather_facts: false

  roles:
    - role: ssh_key
      vars:
        ssh_key_name: "inizio_ssh_key"
    - role: provision
      vars:
        droplet_name: "ubuntu-s-1vcpu-512mb-10gb-fra1-01"

- name: Configure Web Server
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.10

  roles:
    - role: nginx
    - role: ufw


- name: Validate Web Server's reachability
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  
  roles:
    - role: validation
