---
- name: Provision and Configure Secure Web Server on DigitalOcean
  hosts: localhost
  gather_facts: false

  roles:
    - role: ssh_key
      vars:
        ssh_key_name: "inizio_ssh_key"
    - role: provision
      vars:
        droplet_name: "ubuntu-s-1vcpu-512mb-10gb-fra1-01"

- name: Configure Web Server
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.10

  roles:
    - role: nginx

  tasks:
    - name: Validate HTTP response from the server
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}"
        return_content: yes
      register: http_response

    - name: Assert web server is running and serving expected content
      ansible.builtin.assert:
        that:
          - http_response.status == 200
          - '"Deployed with Ansible 🚀" in http_response.content'
