---
- name: Provision and Configure Secure Web Server on DigitalOcean
  hosts: localhost
  gather_facts: false
  vars:
    webserver_name: "static-web-server"
    webserver_public_key_name: "webserver_key"

  roles:
    - role: provision
      vars:
        ssh_key_name: "{{ webserver_public_key_name }}"
        droplet_name: "{{ webserver_name }}"

- name: Configure Web Server
  hosts: webservers
  become: true

  roles:
    - role: webcontent
    - role: nginx

- name: Configure Web Server's security and updates
  hosts: webservers
  become: true

  roles:
    - role: security
    - role: ufw
    - role: updates

- name: Validate Web Server's reachability
  hosts: webservers
  become: true
  
  roles:
    - role: validation
